
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class About extends ContentItem {
    public bannerHeading!: Elements.TextElement;
    public bannerImage!: Elements.AssetsElement;
    public content1!: Elements.RichTextElement;
    public content2!: Elements.RichTextElement;
    public image1!: Elements.AssetsElement;
    public image1content!: Elements.RichTextElement;
    public image2!: Elements.AssetsElement;
    public image2content!: Elements.RichTextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'banner_heading') {
                    return 'bannerHeading';
                }
                if (elementName === 'banner_image') {
                    return 'bannerImage';
                }
                return elementName;
            })
        });
    }
}
