
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Jan 17 2024 10:56:22 GMT+0500 (Pakistan Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Buttons extends ContentItem {
    public name!: Elements.TextElement;
    public link!: Elements.TextElement;
    public target!: Elements.NumberElement;
}
