
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Sep 20 2024 14:47:45 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Exhibitor extends ContentItem {
    public heading!: Elements.TextElement;
    public banner!: Elements.AssetsElement;
    public content!: Elements.TextElement;
    public exhibitorsimages!: Elements.AssetsElement;
    public exhibitorText!: Elements.TextElement;
    public registerHeading!: Elements.TextElement;
    public registerLocale!: Elements.TextElement;
    public registerLink!: Elements.TextElement;
    public exhibitorSection1!: Elements.LinkedItemsElement<ContentItem>;
    public exhibitorSection2!: Elements.LinkedItemsElement<ContentItem>;
    public exhibitorSection3!: Elements.LinkedItemsElement<ContentItem>;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'exhibitor_text') {
                    return 'exhibitorText';
                }
                if (elementName === 'register_heading') {
                    return 'registerHeading';
                }
                if (elementName === 'register_locale') {
                    return 'registerLocale';
                }
                if (elementName === 'register_link') {
                    return 'registerLink';
                }
                if (elementName === 'exhibitor_section_1') {
                    return 'exhibitorSection1';
                }
                if (elementName === 'exhibitor_section_2') {
                    return 'exhibitorSection2';
                }
                if (elementName === 'exhibitor_section_3') {
                    return 'exhibitorSection3';
                }
                return elementName;
            })
        });
    }
}
