
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Feature extends ContentItem {
    public heading!: Elements.TextElement;
    public subHeading!: Elements.TextElement;
    public banner!: Elements.AssetsElement;
    public content!: Elements.TextElement;
    public featureItem!: Elements.LinkedItemsElement<ContentItem>;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'sub_heading') {
                    return 'subHeading';
                }
                if (elementName === 'feature_item') {
                    return 'featureItem';
                }
                return elementName;
            })
        });
    }
}
