
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Featureitem extends ContentItem {
    public heading!: Elements.TextElement;
    public content!: Elements.RichTextElement;
    public backgroundImage!: Elements.AssetsElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'background_image') {
                    return 'backgroundImage';
                }
                return elementName;
            })
        });
    }
}
