
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Mon Sep 23 2024 16:49:16 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Homebanner extends ContentItem {
    public logo!: Elements.AssetsElement;
    public dateandvenu!: Elements.RichTextElement;
    public heading!: Elements.TextElement;
    public slogan!: Elements.TextElement;
    public buttons!: Elements.LinkedItemsElement<ContentItem>;
    public totalvisitors!: Elements.TextElement;
    public totalexhibitors!: Elements.TextElement;
    public totalcountries!: Elements.TextElement;
}
