
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Jul 04 2024 16:47:48 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Homeexhibit extends ContentItem {
    public heading!: Elements.TextElement;
    public content!: Elements.TextElement;
    public image!: Elements.AssetsElement;
    public homeExhibitItem!: Elements.LinkedItemsElement<ContentItem>;
    public quote!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'home_exhibit_item') {
                    return 'homeExhibitItem';
                }
                return elementName;
            })
        });
    }
}
