
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Jul 04 2024 17:01:37 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class WhyVisitSection extends ContentItem {
    public heading!: Elements.TextElement;
    public content!: Elements.RichTextElement;
    public items!: Elements.LinkedItemsElement<ContentItem>;
}
